/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Header file for function displayImage in component cleaningGui.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_H
#define AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "xme/core/component.h"

/******************************************************************************/
/***   Prototypes                                                           ***/
/******************************************************************************/
/**
 * \brief  Initialization of function. 
 *  
 * \details Called once before the function is executed the first time.
 *
 * \param  param Function-specific initialization parameter.
 *
 * \return XME_STATUS_SUCCESS when initialization was successful.
 */
xme_status_t
autopnp_adv_cleaningGui_displayImageFunction_init
(
	void* param
);

/**
 * \brief  Executes the function one time.
 *
 * \details Input ports of the function need to be prepared, before calling this.
 *
 * \param  param Function-specific parameter
 */
void
autopnp_adv_cleaningGui_displayImageFunction_step
(
	void* param
);

/**
 * \brief  Finalization function.
 *
 * \details Called after function will no longer be executed to free allocated resources.
 *          Function must not be executed after teminate has been called.
 */
void
autopnp_adv_cleaningGui_displayImageFunction_fini(void);

#endif // #ifndef AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_H
