/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Source file for function displayImage in component cleaningGui.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "autopnp/adv/cleaningGui/include/displayImageFunction.h"
#include "autopnp/adv/cleaningGui/include/cleaningGuiComponentWrapper.h"

// PROTECTED REGION ID(AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_C_INCLUDES) ENABLED START
#include "xme/core/log.h"

int f(void);
// PROTECTED REGION END


/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
xme_status_t
autopnp_adv_cleaningGui_displayImageFunction_init
(
	void* param
)
{
	// PROTECTED REGION ID(AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_INITIALIZE_C) ENABLED START
	
	// TODO: Auto-generated stub
	
	XME_UNUSED_PARAMETER(param);
	
	return XME_STATUS_SUCCESS;
	
	// PROTECTED REGION END
}

void
autopnp_adv_cleaningGui_displayImageFunction_step
(
	void* param
)
{
	xme_status_t status[1];
	
	autopnp_topic_image_t portImageInData;
	
	status[0] = autopnp_adv_cleaningGui_cleaningGuiComponentWrapper_readPortImageIn(&portImageInData);
	
	{
		// PROTECTED REGION ID(AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_STEP_C) ENABLED START
	
		XME_LOG(XME_LOG_ALWAYS, "Received image with dimensions %ux%u\n", f(), portImageInData.height);

		// TODO: Auto-generated stub
	
		XME_UNUSED_PARAMETER(param);
		XME_UNUSED_PARAMETER(status);
		
		// PROTECTED REGION END
	}
	
}

void
autopnp_adv_cleaningGui_displayImageFunction_fini(void)
{
	// PROTECTED REGION ID(AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_TERMINATE_C) ENABLED START
	
	// TODO: Auto-generated stub
	
	// PROTECTED REGION END
}

// PROTECTED REGION ID(AUTOPNP_ADV_CLEANINGGUI_DISPLAYIMAGEFUNCTION_IMPLEMENTATION_C) ENABLED START

// PROTECTED REGION END
