/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Function wrapper - a generic abstraction for one executable function
 *              scheduled by the execution manager.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include "autopnp/adv/cleaningGui/include/displayImageFunction.h"

#include "autopnp/adv/cleaningGui/include/cleaningGuiComponentWrapper.h"
#include "autopnp/adv/cleaningGui/include/displayImageFunctionWrapper.h"

#include "xme/core/executionManager/include/executionManagerDataStructures.h"
#include "xme/core/executionManager/include/executionManagerWrapperInterface.h"

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
void
autopnp_adv_cleaningGui_displayImageFunctionWrapper_execute
(
	void* userFunctionDescRaw
)
{
	xme_core_exec_functionDescriptor_t* funDesc;
	void* functionParameter;

	funDesc = (xme_core_exec_functionDescriptor_t*)userFunctionDescRaw;
	functionParameter = NULL;

	xme_core_exec_dispatcher_initializeTask
	(
		funDesc->componentId,
		funDesc->functionId
	);

	if (NULL != funDesc->init)
	{
		xme_status_t status = XME_STATUS_INTERNAL_ERROR;

		status = funDesc->init(funDesc->initParam);
		if (XME_STATUS_SUCCESS != status)
		{
			XME_LOG(XME_LOG_FATAL,
					"Function [%d|%d] initialization returned an error code %d\n",
					funDesc->componentId,
					funDesc->functionId,
					status);
			funDesc->state = XME_CORE_EXEC_FUNCTION_STATE_TERMINATED;
		}
	}

    for (;;)
    {
        xme_core_exec_dispatcher_waitForStart
        (
        	funDesc->componentId,
        	funDesc->functionId,
        	&functionParameter
        );

        if (XME_CORE_EXEC_FUNCTION_STATE_TERMINATED == funDesc->state)
        {
            xme_core_exec_dispatcher_executionCompleted
            (
                funDesc->componentId,
                funDesc->functionId
            );
            
            return;
        }

        if (XME_CORE_EXEC_FUNCTION_STATE_PAUSED != funDesc->state)
        {
	        autopnp_adv_cleaningGui_displayImageFunction_step(functionParameter);
	        
	        autopnp_adv_cleaningGui_cleaningGuiComponentWrapper_completeReadOperations();
        }

        xme_core_exec_dispatcher_executionCompleted
        (
            funDesc->componentId,
            funDesc->functionId
        );
	}

    if (NULL != funDesc->fini)
	{
		funDesc->fini();
	}
}
