/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Topic registry extension.
 *         Project specific topic data structures are defined here.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef _TOPICDATA_H
#define _TOPICDATA_H

/******************************************************************************/
/***   Includes                                                             ***/
/******************************************************************************/
#include <stdbool.h>
#include <stdint.h>

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/
/**
 * \struct _topic_image_t
 *
 * \brief  Data type for topic 'image' (identifier: _TOPIC_IMAGE).
 */
#pragma pack(push, 1)
typedef struct
{
	uint32_t height;
	uint32_t width;
	char encoding[20];
	uint8_t isBigEndian;
	uint32_t step;
	uint8_t data[307200];
}
_topic_image_t;
#pragma pack(pop)

#endif // #ifndef _TOPICDATA_H
