/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Function wrapper - a generic abstraction for one executable function
 *              scheduled by the execution manager.
 *
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef AUTOPNP_WP_MARSHALER_MARSHALERRUNFUNCTIONWRAPPER_H
#define AUTOPNP_WP_MARSHALER_MARSHALERRUNFUNCTIONWRAPPER_H

/******************************************************************************/
/***   Implementation                                                       ***/
/******************************************************************************/
void
autopnp_wp_marshaler_marshalerFunctionWrapper_execute
(
	void* param
);

#endif // #ifndef AUTOPNP_WP_MARSHALER_MARSHALERRUNFUNCTIONWRAPPER_H
