/*
 * Copyright (c) 2011-2013, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution. A copy is available at
 * http://chromosome.fortiss.org/.
 *
 * This file is part of CHROMOSOME.
 *
 * $Id$
 */

/**
 * \file
 *         Topic dictionary extension.
 *         Project specific topic and attribute identifiers are defined here.
 *
 * \author
 *         This file has been generated by the CHROMOSOME Modeling Tool (XMT)
 *         (fortiss GmbH).
 */

#ifndef AUTOPNP_TOPIC_H
#define AUTOPNP_TOPIC_H

/******************************************************************************/
/***   Type definitions                                                     ***/
/******************************************************************************/
/**
 * \typedef autopnp_topic_t
 *
 * \brief  Collection of identifiers of all topics used in this dictionary.
 */
typedef enum
{
	AUTOPNP_TOPIC_MIN = 4097, ///< Minimum topic identifier of this dictionary.
	
	AUTOPNP_TOPIC_IMAGE = 4098, ///< image topic (data type: autopnp_topic_image_t).
	
	AUTOPNP_TOPIC_MAX = 5000 ///< Maximum topic identifier of this dictionary.
}
autopnp_topic_t;

#endif // #ifndef AUTOPNP_TOPIC_H
